# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 367)
        Form.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, 50, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.personId = QtWidgets.QLineEdit(Form)
        self.personId.setGeometry(QtCore.QRect(480, 50, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.personId.setFont(font)
        self.personId.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Times New Roman\";")
        self.personId.setObjectName("personId")
        self.photo_label = QtWidgets.QLabel(Form)
        self.photo_label.setGeometry(QtCore.QRect(30, 30, 350, 290))
        self.photo_label.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setGeometry(QtCore.QRect(470, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("color: rgb(4, 1, 1);\n"
"font: 75 25pt \"Times New Roman\";")
        self.searchButton.setObjectName("searchButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "id"))
        self.searchButton.setText(_translate("Form", "Найти"))
